In [ ]:
import numpy as np

# **Question 5**

## *Part 1*

In [ ]:
b = np.arange(24).reshape(6,4)
print(b[1:2,:])

[[4 5 6 7]]


### Self-modification

In [ ]:
b = np.arange(80).reshape(4,20)
print(b[-1:,:])

[[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]]


Basically *np.arange(n)* produces a sequence of integers from 0 to n-1 <br> and *reshape(p,q)* reshapes the sequence into a matrix format (list of lists) : p many lists of q-sized list provided p*q = n

## *Part-2*

In [ ]:
x = np.array([[1,2,9],[4,5,6]])
print(np.max(x, axis=1))

[9 6]


### Self-modification

In [ ]:
x = np.array([[1,2],[4,5],[6,7]])
print(np.max(x, axis=0))

[6 7]


## *Part-3*

In [ ]:
x = np.arange(1,10).reshape(3,3)
print(np.sum(x,axis=0))

[12 15 18]


### Self-modification

In [ ]:
x = np.arange(1,11).reshape(5,2)
print(np.sum(x,axis=1))

[ 3  7 11 15 19]


## *Part-4*

In [ ]:
g = np.arange(24)
g2 = g.reshape(4,6)
print(g.ndim)
print(g2.ndim)

1
2


### Self-modification

In [ ]:
g = np.arange(26)
g2 = g.reshape(2,13)
g3 = g2.reshape(13,2)
print(g.ndim)
print(g3.ndim)

1
2


## *Part-5*

In [ ]:
m = np.array([20,-5,30,40])
print(m<[15,16,35,36])

[False  True  True False]


### Self-modification

In [ ]:
m = np.array([2,-5,30.1,40.9])
print(m<[25,6,29,40])

[ True  True False False]


## *Part-6*

In [ ]:
m = np.array([20,-5,30,40])
print(m[m<25])

[20 -5]


### Self-modification

In [ ]:
m = np.array([-1,-2,-4,-6])
print(m[m>0])

[]


## *Part-7*

In [ ]:
a = np.array([1,5,3,19,13,7,3])
print(a[1:2])
print(a[1::2])

[5]
[ 5 19  7]


### Self-modification

In [ ]:
a = np.array([43,6,726,2,47,78])
print(a[3:-2])
print(a[-1::-2])

[2]
[78  2  6]


## *Part-8*

In [ ]:
import pandas as pd
people = pd.DataFrame({
    "birthyear" : {"alice":1985,"bob":1984,"charles":1992},
    "hobby" : {"alice":"Biking","bob":"Dancing"},
    "weight" : {"alice":68,"bob":83,"charles":112}
})
print(people.iloc[2])
print("\n\n")
print(people[people["weight"]>80])

birthyear    1992
hobby         NaN
weight        112
Name: charles, dtype: object

Next output

         birthyear    hobby  weight
bob           1984  Dancing      83
charles       1992      NaN     112


### Self-modification

In [ ]:
import pandas as pd
people = pd.DataFrame({
    "birthyear" : {"darpan":1980,"james":2001,"soham":2006},
    "hobby" : {"darpan":"coding","soham":"eating"},
    "weight" : {"darpan":608,"james":183,"soham":12}
})
print(people.iloc[-1])
print("\n\n")
print(people[people["weight"]>100])

birthyear      2006
hobby        eating
weight           12
Name: soham, dtype: object



        birthyear   hobby  weight
darpan       1980  coding     608
james        2001     NaN     183


# **Question 1.8**

In [ ]:
import pandas as pd
import numpy as np
Salary = pd.DataFrame({
    "bonus" : [300,3111,np.nan,4333,300,5000,np.nan,10000,300,3432,1,900]
})

In [ ]:
Salary

,bonus
0,300.0
1,3111.0
2,NaN
3,4333.0
4,5000.0
5,NaN
6,10000.0
7,3432.0
8,1.0
9,900.0


In [ ]:
# using the mean as a replacement value for the NaN values

mean_bonus = Salary.bonus.mean()
print('Mean = ',mean_bonus)
Salary_imputedWithMean = Salary.fillna(mean_bonus)
print('New DataFrame:\n',Salary_imputedWithMean)

Mean =  2767.7
New DataFrame:
       bonus
0     300.0
1    3111.0
2    2767.7
3    4333.0
4     300.0
5    5000.0
6    2767.7
7   10000.0
8     300.0
9    3432.0
10      1.0
11    900.0


In [ ]:
# using the median as a replacement value for the NaN values

median_bonus = Salary.bonus.median()
print('Median = ',median_bonus)
Salary_imputedWithMedian = Salary.fillna(median_bonus)
print('New DataFrame:\n',Salary_imputedWithMedian)

Median =  2005.5
New DataFrame:
       bonus
0     300.0
1    3111.0
2    2005.5
3    4333.0
4     300.0
5    5000.0
6    2005.5
7   10000.0
8     300.0
9    3432.0
10      1.0
11    900.0


In [ ]:
# using the mode as a replacement value for the NaN values

mode_bonus = Salary.bonus.mode()
print(f'Number of Modes = {len(mode_bonus)}')
if len(mode_bonus) == 2:
  print(f'Mode = {mode_bonus}')
else:
  print(f'Mode = {mode_bonus[0]}')
Salary_imputedWithMode = Salary.fillna(mode_bonus)
print('New DataFrame:\n',Salary_imputedWithMode)

Number of Modes = 1
Mode = 300.0
New DataFrame:
       bonus
0     300.0
1    3111.0
2       NaN
3    4333.0
4     300.0
5    5000.0
6       NaN
7   10000.0
8     300.0
9    3432.0
10      1.0
11    900.0
